### ISSUE TITLE
'process' is not defined

### ISSUE THREAD

**Issue by danwenzel** [miherlosev/eslint-plugin-testcafe#6]
If you try to access an environment variable using `process.env` ([as instructed by the testcafe docs](https://devexpress.github.io/testcafe/documentation/recipes/access-environment-variables-in-tests.html#access-environment-variables)), eslint throws `'process' is not defined`.

I believe we need to add `node: true` to the `env` config:

```js
env: {
  node: true
},
```

**Comment by miherlosev** [comment]
Hi @danwenzel 

Environment option of the `eslint` tool is a basic option. It should not be set-up in the plugin.
To fix this problem, specify the `env` option in the `.eslint` configuration file.

**Comment by danwenzel** [comment]
Ah, that makes sense.  I was thinking we could set the `env` automatically for anyone using the plugin, but I see now that that's not the eslint convention.  Thanks!
